hms_udn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from participants import views

urlpatterns = [
    url(r'', include('participants.urls')),
    url(r'^admin/', admin.site.urls),
]

participants/urls.py
from django.conf.urls import url
from . import views

app_name = "participants"
urlpatterns = [
    url(r'^$', views.ParticipantList.as_view(), name='index'),
    url(r'^participants/$', views.ParticipantList.as_view(), name='index'),
    url(r'^participants/new$', views.ParticipantCreate.as_view(), name='new'),
    url(r'^participants/(?P<pk>[0-9]+)/$', views.ParticipantUpdate.as_view(), name='detail'),
    url(r'^participants/create$', views.ParticipantCreate, name='create'),
    url(r'^participants/(?P<participant_id>[0-9]+)/update$', views.ParticipantUpdate, name='update'),
    url(r'^participants/(?P<participant_id>[0-9]+)/delete$', views.ParticipantDelete, name='delete'),
]

participants/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Participant(models.Model):
    name = models.CharField(max_length=100, blank=False)
    age = models.CharField(max_length=3, blank=False)

    UMM_YES = "YES"
    SAY_NO = "NO"
    YES_NO_CHOICES = ((UMM_YES, 'Yes'), (SAY_NO, "No"))
    siblings = models.CharField(
        max_length=3,
        choices=YES_NO_CHOICES,
        default=SAY_NO)

    env_exposures = models.CharField(max_length=300, blank=True)
    genetic_mutations = models.CharField(max_length=300, blank=True)

    NOT_REVIEWED = 'NR'
    REVIEWED_ACCEPTED = 'RA'
    REVIEWED_NOT_ACCEPTED = 'RN'
    STATUS_CHOICES = (
        (NOT_REVIEWED, 'Not Reviewed'),
        (REVIEWED_ACCEPTED, 'Reviewed - Accepted'),
        (REVIEWED_NOT_ACCEPTED, 'Reviewed - Not Accepted'))
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default=NOT_REVIEWED)

    def __str__(self):
        return self.name
    def is_juvenile(self):
        return int(self.age) < 18

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

participants/forms.py
from django import forms

class ParticipantForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True)
    age = forms.CharField(max_length=3, required=True)
    UMM_YES = "YES"
    SAY_NO = "NO"
    YES_NO_CHOICES = ((UMM_YES, 'Yes'), (SAY_NO, "No"))
    siblings = forms.CharField(max_length=3,
                               widget=forms.Select(choices=YES_NO_CHOICES))
    env_exposures = forms.CharField(widget=forms.Textarea(attrs={'max_length':300, 'required':False}))
    genetic_mutations = forms.CharField(widget=forms.Textarea,
                                        max_length=300,
                                        required=False)

    NOT_REVIEWED = 'NR'
    REVIEWED_ACCEPTED = 'RA'
    REVIEWED_NOT_ACCEPTED = 'RN'
    STATUS_CHOICES = (
        (NOT_REVIEWED, 'Not Reviewed'),
        (REVIEWED_ACCEPTED, 'Reviewed - Accepted'),
        (REVIEWED_NOT_ACCEPTED, 'Reviewed - Not Accepted'))
    status = forms.CharField(max_length=2,
                             widget=forms.Select(choices=STATUS_CHOICES))

    def create_participant(self):
        pass
    def update_participant(self):
        pass

participants/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ParticipantForm
from .models import Participant

class ParticipantCreate(CreateView):
    model = Participant
    fields = ['name', 'age', 'siblings', 'env_exposures', 'genetic_mutations']
    success_url = reverse_lazy('participants:index')

class ParticipantUpdate(UpdateView):
    model = Participant
    fields = ['name', 'age', 'siblings', 'env_exposures', 'genetic_mutations']
    success_url = reverse_lazy('participants:index')

class ParticipantDelete(DeleteView):
    model = Participant
    success_url = reverse_lazy('participants:index')

class AjaxableResponseMixin(object):
    """Adding AJAX support to the index/list view"""

class ParticipantList(ListView):
    model = Participant

    def post(self, request, *args, **kwargs):
        id = request.POST.get('id')
        status = request.POST.get('status')
        ppt = Participant.objects.get(pk=id)
        ppt.status = status
        ppt.save()
        return HttpResponse({'participant_list': Participant.objects.all()})

participants/templates/participants/base.html
{% load staticfiles %}
<html>
  <head>
    <title>HMS UDN</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/participants.css' %}">
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
  <footer>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="{% static "javascript/participants-list.js" %}" type="text/javascript"></script>
  </footer>
</html>

participants/templates/participants/participant_form.html
{% extends 'participants/base.html' %}
{% block content %}
  <h1>Participant Form</h1>
  <div class="container custom-border">
  <form url method="post">
    {% csrf_token %}
    <fieldset class="module aligned participant-form">
      <div class="form-group">
        <label for="{{ form.name.id_for_label }}">Name:</label>
        {% if form.name.errors %}<div class="error"><p><strong>{{ form.name.errors }}{% endif %}
        {{ form.name }}
      </div>

      <div class="form-group">
        <label for="{{ form.age.id_for_label }}">Age:</label>
        {% if form.age.errors %}<div class="error"><p><strong>{{ form.age.errors }}{% endif %}
        {{ form.age }}
      </div>

      <div class="form-group">
        <label for="{{ form.siblings.id_for_label }}">Siblings?</label>
        {% if form.siblings.errors %}<div class="error"><p><strong>{{ form.siblings.errors }}{% endif %}
        {{ form.siblings }}
      </div>

      <div class="form-group">
        <label for="{{ form.env_exposures.id_for_label }}">Please list any environmental exposures:</label>
        {% if form.env_exposures.errors %}<div class="error"><p><strong>{{ form.env_exposures.errors }}{% endif %}
        {{ form.env_exposures }}
      </div>

      <div class="form-group">
        <label for="{{ form.genetic_mutations.id_for_label }}">Please describe any known genetic mutations:</label>
        {% if form.genetic_mutations.errors %}<div class="error"><p><strong>{{ form.genetic_mutations.errors }}{% endif %}
        {{ form.genetic_mutations }}
      </div>
    </fieldset>
    <input class="btn btn-primary" type="submit" value="Submit" />
    <a class="btn btn-default" href="{% url 'participants:index' %}">Cancel</a>
  </form>
</div>
{% endblock %}

participants/templates/participants/participant_list.html
{% extends 'participants/base.html' %}
{% block content %}
  <h1>UDN Particpants</h1>

  {% if message %}
  <div class="alert alert-primary" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>{{ message }}</strong>
  </div>
  {% endif %}

  <div>
    <a class="btn btn-primary btn-add" href="{% url 'participants:new' %}">+ Add Participant</a>
  </div>
  {% if participant_list %}
      <table class="table-bordered table-striped">
        <thead>
          <tr>
            <th>Name:</th>
            <th>Status:</th>
            <th>Age:</th>
            <th>Siblings:</th>
            <th>Environmental Exposures:</th>
            <th>Genetic Mutations:</th>
          </tr>
        </thead>
        <tbody>
      {% for ppt in participant_list %}
          <tr>
            <td><a href="{% url 'participants:detail' ppt.id %}">{{ ppt.name }}</a></td>
            <td>
              <select class=status onchange="update_status({{ppt.pk}}, this.options[this.selectedIndex].value)">
                <option value="NR" {% if ppt.status == "NR" %}selected="selected"{% endif %}>Not Reviewed</option>
                <option value="RA" {% if ppt.status == "RA" %}selected="selected"{% endif %}>Reviewed - Accepted</option>
                <option value="RN" {% if ppt.status == "RN" %}selected="selected"{% endif %}>Reviewed - Not Accepted</option>
              </select>
            </td>
            <td>{{ ppt.age }}</td>
            <td>{{ ppt.siblings }}</td>
            <td>{{ ppt.env_exposures }}</td>
            <td>{{ ppt.genetic_mutations }}</td>
          </tr>
      {% endfor %}
        </tbody>
      </table>
  {% else %}
      <p>No participants are available.</p>
  {% endif %}
{% endblock %}